### ISSUE TITLE
suggestions for improvement

### ISSUE THREAD

**Issue by RuesanG** [ionuttbara/redist-pack#4]
Hello this package is useful for fresh installation

What bothers me is that the Net Framework pack is actually enough for users who need the .NET Desktop Runtime

And the .NET Core  from the pack cannot be updated via Windows Update. 
You would have to uninstall them and download them directly from Microsoft in order to update them in Windows Update.

**Comment by ionuttbara** [comment]
Because the .net core is installed from .msi files.
Downloading .exe setup from microsoft website, it installs .net core twice (downloaded .net core , .net desktop runtime)
